export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILED='LOGIN_FAILED';

export const AUTHENTICATE_USER='AUTHENTICATE_USER';
export const LOG_OUT='LOG_OUT';

export const SIGNUP_START='SIGNUP_START';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_FAILED='SIGNUP_FAILED'


export const CLEAR_AUTH_STATE='CLEAR_AUTH_STATE'

export const UPDATE_EVENTS='UPDATE_EVENTS'
export const POST_EVENT_START='POST_EVENT_START'
export const POST_EVENT_SUCCESS='POST_EVENT_SUCCESS'
export const POST_EVENT_FAILURE='POST_EVENT_FAILURE'